// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/contracts/security_scanner.proto

package contracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScannerModuleConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SastBackend      string                 `protobuf:"bytes,1,opt,name=sast_backend,json=sastBackend,proto3" json:"sast_backend,omitempty"`
	ContainerBackend string                 `protobuf:"bytes,2,opt,name=container_backend,json=containerBackend,proto3" json:"container_backend,omitempty"`
	DepsBackend      string                 `protobuf:"bytes,3,opt,name=deps_backend,json=depsBackend,proto3" json:"deps_backend,omitempty"`
	MockFindings     []*Finding             `protobuf:"bytes,4,rep,name=mock_findings,json=mockFindings,proto3" json:"mock_findings,omitempty"`
	MockPassed       bool                   `protobuf:"varint,5,opt,name=mock_passed,json=mockPassed,proto3" json:"mock_passed,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ScannerModuleConfig) Reset() {
	*x = ScannerModuleConfig{}
	mi := &file_internal_contracts_security_scanner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScannerModuleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScannerModuleConfig) ProtoMessage() {}

func (x *ScannerModuleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_security_scanner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScannerModuleConfig.ProtoReflect.Descriptor instead.
func (*ScannerModuleConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_security_scanner_proto_rawDescGZIP(), []int{0}
}

func (x *ScannerModuleConfig) GetSastBackend() string {
	if x != nil {
		return x.SastBackend
	}
	return ""
}

func (x *ScannerModuleConfig) GetContainerBackend() string {
	if x != nil {
		return x.ContainerBackend
	}
	return ""
}

func (x *ScannerModuleConfig) GetDepsBackend() string {
	if x != nil {
		return x.DepsBackend
	}
	return ""
}

func (x *ScannerModuleConfig) GetMockFindings() []*Finding {
	if x != nil {
		return x.MockFindings
	}
	return nil
}

func (x *ScannerModuleConfig) GetMockPassed() bool {
	if x != nil {
		return x.MockPassed
	}
	return false
}

type SASTScanConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Scanner        string                 `protobuf:"bytes,1,opt,name=scanner,proto3" json:"scanner,omitempty"`
	SourcePath     string                 `protobuf:"bytes,2,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	Rules          []string               `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	FailOnSeverity string                 `protobuf:"bytes,4,opt,name=fail_on_severity,json=failOnSeverity,proto3" json:"fail_on_severity,omitempty"`
	OutputFormat   string                 `protobuf:"bytes,5,opt,name=output_format,json=outputFormat,proto3" json:"output_format,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SASTScanConfig) Reset() {
	*x = SASTScanConfig{}
	mi := &file_internal_contracts_security_scanner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SASTScanConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SASTScanConfig) ProtoMessage() {}

func (x *SASTScanConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_security_scanner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SASTScanConfig.ProtoReflect.Descriptor instead.
func (*SASTScanConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_security_scanner_proto_rawDescGZIP(), []int{1}
}

func (x *SASTScanConfig) GetScanner() string {
	if x != nil {
		return x.Scanner
	}
	return ""
}

func (x *SASTScanConfig) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *SASTScanConfig) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *SASTScanConfig) GetFailOnSeverity() string {
	if x != nil {
		return x.FailOnSeverity
	}
	return ""
}

func (x *SASTScanConfig) GetOutputFormat() string {
	if x != nil {
		return x.OutputFormat
	}
	return ""
}

type SASTScanInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Scanner        string                 `protobuf:"bytes,1,opt,name=scanner,proto3" json:"scanner,omitempty"`
	SourcePath     string                 `protobuf:"bytes,2,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	Rules          []string               `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	FailOnSeverity string                 `protobuf:"bytes,4,opt,name=fail_on_severity,json=failOnSeverity,proto3" json:"fail_on_severity,omitempty"`
	OutputFormat   string                 `protobuf:"bytes,5,opt,name=output_format,json=outputFormat,proto3" json:"output_format,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SASTScanInput) Reset() {
	*x = SASTScanInput{}
	mi := &file_internal_contracts_security_scanner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SASTScanInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SASTScanInput) ProtoMessage() {}

func (x *SASTScanInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_security_scanner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SASTScanInput.ProtoReflect.Descriptor instead.
func (*SASTScanInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_security_scanner_proto_rawDescGZIP(), []int{2}
}

func (x *SASTScanInput) GetScanner() string {
	if x != nil {
		return x.Scanner
	}
	return ""
}

func (x *SASTScanInput) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *SASTScanInput) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *SASTScanInput) GetFailOnSeverity() string {
	if x != nil {
		return x.FailOnSeverity
	}
	return ""
}

func (x *SASTScanInput) GetOutputFormat() string {
	if x != nil {
		return x.OutputFormat
	}
	return ""
}

type ContainerScanConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Scanner           string                 `protobuf:"bytes,1,opt,name=scanner,proto3" json:"scanner,omitempty"`
	TargetImage       string                 `protobuf:"bytes,2,opt,name=target_image,json=targetImage,proto3" json:"target_image,omitempty"`
	SeverityThreshold string                 `protobuf:"bytes,3,opt,name=severity_threshold,json=severityThreshold,proto3" json:"severity_threshold,omitempty"`
	IgnoreUnfixed     bool                   `protobuf:"varint,4,opt,name=ignore_unfixed,json=ignoreUnfixed,proto3" json:"ignore_unfixed,omitempty"`
	OutputFormat      string                 `protobuf:"bytes,5,opt,name=output_format,json=outputFormat,proto3" json:"output_format,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ContainerScanConfig) Reset() {
	*x = ContainerScanConfig{}
	mi := &file_internal_contracts_security_scanner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerScanConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerScanConfig) ProtoMessage() {}

func (x *ContainerScanConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_security_scanner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerScanConfig.ProtoReflect.Descriptor instead.
func (*ContainerScanConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_security_scanner_proto_rawDescGZIP(), []int{3}
}

func (x *ContainerScanConfig) GetScanner() string {
	if x != nil {
		return x.Scanner
	}
	return ""
}

func (x *ContainerScanConfig) GetTargetImage() string {
	if x != nil {
		return x.TargetImage
	}
	return ""
}

func (x *ContainerScanConfig) GetSeverityThreshold() string {
	if x != nil {
		return x.SeverityThreshold
	}
	return ""
}

func (x *ContainerScanConfig) GetIgnoreUnfixed() bool {
	if x != nil {
		return x.IgnoreUnfixed
	}
	return false
}

func (x *ContainerScanConfig) GetOutputFormat() string {
	if x != nil {
		return x.OutputFormat
	}
	return ""
}

type ContainerScanInput struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Scanner           string                 `protobuf:"bytes,1,opt,name=scanner,proto3" json:"scanner,omitempty"`
	TargetImage       string                 `protobuf:"bytes,2,opt,name=target_image,json=targetImage,proto3" json:"target_image,omitempty"`
	SeverityThreshold string                 `protobuf:"bytes,3,opt,name=severity_threshold,json=severityThreshold,proto3" json:"severity_threshold,omitempty"`
	IgnoreUnfixed     bool                   `protobuf:"varint,4,opt,name=ignore_unfixed,json=ignoreUnfixed,proto3" json:"ignore_unfixed,omitempty"`
	OutputFormat      string                 `protobuf:"bytes,5,opt,name=output_format,json=outputFormat,proto3" json:"output_format,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ContainerScanInput) Reset() {
	*x = ContainerScanInput{}
	mi := &file_internal_contracts_security_scanner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerScanInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerScanInput) ProtoMessage() {}

func (x *ContainerScanInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_security_scanner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerScanInput.ProtoReflect.Descriptor instead.
func (*ContainerScanInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_security_scanner_proto_rawDescGZIP(), []int{4}
}

func (x *ContainerScanInput) GetScanner() string {
	if x != nil {
		return x.Scanner
	}
	return ""
}

func (x *ContainerScanInput) GetTargetImage() string {
	if x != nil {
		return x.TargetImage
	}
	return ""
}

func (x *ContainerScanInput) GetSeverityThreshold() string {
	if x != nil {
		return x.SeverityThreshold
	}
	return ""
}

func (x *ContainerScanInput) GetIgnoreUnfixed() bool {
	if x != nil {
		return x.IgnoreUnfixed
	}
	return false
}

func (x *ContainerScanInput) GetOutputFormat() string {
	if x != nil {
		return x.OutputFormat
	}
	return ""
}

type DepsScanConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Scanner        string                 `protobuf:"bytes,1,opt,name=scanner,proto3" json:"scanner,omitempty"`
	SourcePath     string                 `protobuf:"bytes,2,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	FailOnSeverity string                 `protobuf:"bytes,3,opt,name=fail_on_severity,json=failOnSeverity,proto3" json:"fail_on_severity,omitempty"`
	OutputFormat   string                 `protobuf:"bytes,4,opt,name=output_format,json=outputFormat,proto3" json:"output_format,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DepsScanConfig) Reset() {
	*x = DepsScanConfig{}
	mi := &file_internal_contracts_security_scanner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepsScanConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepsScanConfig) ProtoMessage() {}

func (x *DepsScanConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_security_scanner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepsScanConfig.ProtoReflect.Descriptor instead.
func (*DepsScanConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_security_scanner_proto_rawDescGZIP(), []int{5}
}

func (x *DepsScanConfig) GetScanner() string {
	if x != nil {
		return x.Scanner
	}
	return ""
}

func (x *DepsScanConfig) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *DepsScanConfig) GetFailOnSeverity() string {
	if x != nil {
		return x.FailOnSeverity
	}
	return ""
}

func (x *DepsScanConfig) GetOutputFormat() string {
	if x != nil {
		return x.OutputFormat
	}
	return ""
}

type DepsScanInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Scanner        string                 `protobuf:"bytes,1,opt,name=scanner,proto3" json:"scanner,omitempty"`
	SourcePath     string                 `protobuf:"bytes,2,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	FailOnSeverity string                 `protobuf:"bytes,3,opt,name=fail_on_severity,json=failOnSeverity,proto3" json:"fail_on_severity,omitempty"`
	OutputFormat   string                 `protobuf:"bytes,4,opt,name=output_format,json=outputFormat,proto3" json:"output_format,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DepsScanInput) Reset() {
	*x = DepsScanInput{}
	mi := &file_internal_contracts_security_scanner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepsScanInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepsScanInput) ProtoMessage() {}

func (x *DepsScanInput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_security_scanner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepsScanInput.ProtoReflect.Descriptor instead.
func (*DepsScanInput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_security_scanner_proto_rawDescGZIP(), []int{6}
}

func (x *DepsScanInput) GetScanner() string {
	if x != nil {
		return x.Scanner
	}
	return ""
}

func (x *DepsScanInput) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *DepsScanInput) GetFailOnSeverity() string {
	if x != nil {
		return x.FailOnSeverity
	}
	return ""
}

func (x *DepsScanInput) GetOutputFormat() string {
	if x != nil {
		return x.OutputFormat
	}
	return ""
}

type ScanSASTRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Scanner        string                 `protobuf:"bytes,1,opt,name=scanner,proto3" json:"scanner,omitempty"`
	SourcePath     string                 `protobuf:"bytes,2,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	Rules          []string               `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	FailOnSeverity string                 `protobuf:"bytes,4,opt,name=fail_on_severity,json=failOnSeverity,proto3" json:"fail_on_severity,omitempty"`
	OutputFormat   string                 `protobuf:"bytes,5,opt,name=output_format,json=outputFormat,proto3" json:"output_format,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScanSASTRequest) Reset() {
	*x = ScanSASTRequest{}
	mi := &file_internal_contracts_security_scanner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanSASTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanSASTRequest) ProtoMessage() {}

func (x *ScanSASTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_security_scanner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanSASTRequest.ProtoReflect.Descriptor instead.
func (*ScanSASTRequest) Descriptor() ([]byte, []int) {
	return file_internal_contracts_security_scanner_proto_rawDescGZIP(), []int{7}
}

func (x *ScanSASTRequest) GetScanner() string {
	if x != nil {
		return x.Scanner
	}
	return ""
}

func (x *ScanSASTRequest) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *ScanSASTRequest) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *ScanSASTRequest) GetFailOnSeverity() string {
	if x != nil {
		return x.FailOnSeverity
	}
	return ""
}

func (x *ScanSASTRequest) GetOutputFormat() string {
	if x != nil {
		return x.OutputFormat
	}
	return ""
}

type ScanContainerRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Scanner           string                 `protobuf:"bytes,1,opt,name=scanner,proto3" json:"scanner,omitempty"`
	TargetImage       string                 `protobuf:"bytes,2,opt,name=target_image,json=targetImage,proto3" json:"target_image,omitempty"`
	SeverityThreshold string                 `protobuf:"bytes,3,opt,name=severity_threshold,json=severityThreshold,proto3" json:"severity_threshold,omitempty"`
	IgnoreUnfixed     bool                   `protobuf:"varint,4,opt,name=ignore_unfixed,json=ignoreUnfixed,proto3" json:"ignore_unfixed,omitempty"`
	OutputFormat      string                 `protobuf:"bytes,5,opt,name=output_format,json=outputFormat,proto3" json:"output_format,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ScanContainerRequest) Reset() {
	*x = ScanContainerRequest{}
	mi := &file_internal_contracts_security_scanner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanContainerRequest) ProtoMessage() {}

func (x *ScanContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_security_scanner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanContainerRequest.ProtoReflect.Descriptor instead.
func (*ScanContainerRequest) Descriptor() ([]byte, []int) {
	return file_internal_contracts_security_scanner_proto_rawDescGZIP(), []int{8}
}

func (x *ScanContainerRequest) GetScanner() string {
	if x != nil {
		return x.Scanner
	}
	return ""
}

func (x *ScanContainerRequest) GetTargetImage() string {
	if x != nil {
		return x.TargetImage
	}
	return ""
}

func (x *ScanContainerRequest) GetSeverityThreshold() string {
	if x != nil {
		return x.SeverityThreshold
	}
	return ""
}

func (x *ScanContainerRequest) GetIgnoreUnfixed() bool {
	if x != nil {
		return x.IgnoreUnfixed
	}
	return false
}

func (x *ScanContainerRequest) GetOutputFormat() string {
	if x != nil {
		return x.OutputFormat
	}
	return ""
}

type ScanDepsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Scanner        string                 `protobuf:"bytes,1,opt,name=scanner,proto3" json:"scanner,omitempty"`
	SourcePath     string                 `protobuf:"bytes,2,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	FailOnSeverity string                 `protobuf:"bytes,3,opt,name=fail_on_severity,json=failOnSeverity,proto3" json:"fail_on_severity,omitempty"`
	OutputFormat   string                 `protobuf:"bytes,4,opt,name=output_format,json=outputFormat,proto3" json:"output_format,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScanDepsRequest) Reset() {
	*x = ScanDepsRequest{}
	mi := &file_internal_contracts_security_scanner_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanDepsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanDepsRequest) ProtoMessage() {}

func (x *ScanDepsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_security_scanner_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanDepsRequest.ProtoReflect.Descriptor instead.
func (*ScanDepsRequest) Descriptor() ([]byte, []int) {
	return file_internal_contracts_security_scanner_proto_rawDescGZIP(), []int{9}
}

func (x *ScanDepsRequest) GetScanner() string {
	if x != nil {
		return x.Scanner
	}
	return ""
}

func (x *ScanDepsRequest) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *ScanDepsRequest) GetFailOnSeverity() string {
	if x != nil {
		return x.FailOnSeverity
	}
	return ""
}

func (x *ScanDepsRequest) GetOutputFormat() string {
	if x != nil {
		return x.OutputFormat
	}
	return ""
}

type Finding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Line          int32                  `protobuf:"varint,5,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_internal_contracts_security_scanner_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_security_scanner_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_internal_contracts_security_scanner_proto_rawDescGZIP(), []int{10}
}

func (x *Finding) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *Finding) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Finding) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Finding) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Finding) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

type Summary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Critical      int32                  `protobuf:"varint,1,opt,name=critical,proto3" json:"critical,omitempty"`
	High          int32                  `protobuf:"varint,2,opt,name=high,proto3" json:"high,omitempty"`
	Medium        int32                  `protobuf:"varint,3,opt,name=medium,proto3" json:"medium,omitempty"`
	Low           int32                  `protobuf:"varint,4,opt,name=low,proto3" json:"low,omitempty"`
	Info          int32                  `protobuf:"varint,5,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Summary) Reset() {
	*x = Summary{}
	mi := &file_internal_contracts_security_scanner_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Summary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Summary) ProtoMessage() {}

func (x *Summary) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_security_scanner_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Summary.ProtoReflect.Descriptor instead.
func (*Summary) Descriptor() ([]byte, []int) {
	return file_internal_contracts_security_scanner_proto_rawDescGZIP(), []int{11}
}

func (x *Summary) GetCritical() int32 {
	if x != nil {
		return x.Critical
	}
	return 0
}

func (x *Summary) GetHigh() int32 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Summary) GetMedium() int32 {
	if x != nil {
		return x.Medium
	}
	return 0
}

func (x *Summary) GetLow() int32 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Summary) GetInfo() int32 {
	if x != nil {
		return x.Info
	}
	return 0
}

type ScanOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scanner       string                 `protobuf:"bytes,1,opt,name=scanner,proto3" json:"scanner,omitempty"`
	PassedGate    bool                   `protobuf:"varint,2,opt,name=passed_gate,json=passedGate,proto3" json:"passed_gate,omitempty"`
	Findings      []*Finding             `protobuf:"bytes,3,rep,name=findings,proto3" json:"findings,omitempty"`
	Summary       *Summary               `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Error         string                 `protobuf:"bytes,100,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanOutput) Reset() {
	*x = ScanOutput{}
	mi := &file_internal_contracts_security_scanner_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanOutput) ProtoMessage() {}

func (x *ScanOutput) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_security_scanner_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanOutput.ProtoReflect.Descriptor instead.
func (*ScanOutput) Descriptor() ([]byte, []int) {
	return file_internal_contracts_security_scanner_proto_rawDescGZIP(), []int{12}
}

func (x *ScanOutput) GetScanner() string {
	if x != nil {
		return x.Scanner
	}
	return ""
}

func (x *ScanOutput) GetPassedGate() bool {
	if x != nil {
		return x.PassedGate
	}
	return false
}

func (x *ScanOutput) GetFindings() []*Finding {
	if x != nil {
		return x.Findings
	}
	return nil
}

func (x *ScanOutput) GetSummary() *Summary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *ScanOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_contracts_security_scanner_proto protoreflect.FileDescriptor

const file_internal_contracts_security_scanner_proto_rawDesc = "" +
	"\n" +
	")internal/contracts/security_scanner.proto\x12$workflow.plugins.security_scanner.v1\"\xfd\x01\n" +
	"\x13ScannerModuleConfig\x12!\n" +
	"\fsast_backend\x18\x01 \x01(\tR\vsastBackend\x12+\n" +
	"\x11container_backend\x18\x02 \x01(\tR\x10containerBackend\x12!\n" +
	"\fdeps_backend\x18\x03 \x01(\tR\vdepsBackend\x12R\n" +
	"\rmock_findings\x18\x04 \x03(\v2-.workflow.plugins.security_scanner.v1.FindingR\fmockFindings\x12\x1f\n" +
	"\vmock_passed\x18\x05 \x01(\bR\n" +
	"mockPassed\"\xb0\x01\n" +
	"\x0eSASTScanConfig\x12\x18\n" +
	"\ascanner\x18\x01 \x01(\tR\ascanner\x12\x1f\n" +
	"\vsource_path\x18\x02 \x01(\tR\n" +
	"sourcePath\x12\x14\n" +
	"\x05rules\x18\x03 \x03(\tR\x05rules\x12(\n" +
	"\x10fail_on_severity\x18\x04 \x01(\tR\x0efailOnSeverity\x12#\n" +
	"\routput_format\x18\x05 \x01(\tR\foutputFormat\"\xaf\x01\n" +
	"\rSASTScanInput\x12\x18\n" +
	"\ascanner\x18\x01 \x01(\tR\ascanner\x12\x1f\n" +
	"\vsource_path\x18\x02 \x01(\tR\n" +
	"sourcePath\x12\x14\n" +
	"\x05rules\x18\x03 \x03(\tR\x05rules\x12(\n" +
	"\x10fail_on_severity\x18\x04 \x01(\tR\x0efailOnSeverity\x12#\n" +
	"\routput_format\x18\x05 \x01(\tR\foutputFormat\"\xcd\x01\n" +
	"\x13ContainerScanConfig\x12\x18\n" +
	"\ascanner\x18\x01 \x01(\tR\ascanner\x12!\n" +
	"\ftarget_image\x18\x02 \x01(\tR\vtargetImage\x12-\n" +
	"\x12severity_threshold\x18\x03 \x01(\tR\x11severityThreshold\x12%\n" +
	"\x0eignore_unfixed\x18\x04 \x01(\bR\rignoreUnfixed\x12#\n" +
	"\routput_format\x18\x05 \x01(\tR\foutputFormat\"\xcc\x01\n" +
	"\x12ContainerScanInput\x12\x18\n" +
	"\ascanner\x18\x01 \x01(\tR\ascanner\x12!\n" +
	"\ftarget_image\x18\x02 \x01(\tR\vtargetImage\x12-\n" +
	"\x12severity_threshold\x18\x03 \x01(\tR\x11severityThreshold\x12%\n" +
	"\x0eignore_unfixed\x18\x04 \x01(\bR\rignoreUnfixed\x12#\n" +
	"\routput_format\x18\x05 \x01(\tR\foutputFormat\"\x9a\x01\n" +
	"\x0eDepsScanConfig\x12\x18\n" +
	"\ascanner\x18\x01 \x01(\tR\ascanner\x12\x1f\n" +
	"\vsource_path\x18\x02 \x01(\tR\n" +
	"sourcePath\x12(\n" +
	"\x10fail_on_severity\x18\x03 \x01(\tR\x0efailOnSeverity\x12#\n" +
	"\routput_format\x18\x04 \x01(\tR\foutputFormat\"\x99\x01\n" +
	"\rDepsScanInput\x12\x18\n" +
	"\ascanner\x18\x01 \x01(\tR\ascanner\x12\x1f\n" +
	"\vsource_path\x18\x02 \x01(\tR\n" +
	"sourcePath\x12(\n" +
	"\x10fail_on_severity\x18\x03 \x01(\tR\x0efailOnSeverity\x12#\n" +
	"\routput_format\x18\x04 \x01(\tR\foutputFormat\"\xb1\x01\n" +
	"\x0fScanSASTRequest\x12\x18\n" +
	"\ascanner\x18\x01 \x01(\tR\ascanner\x12\x1f\n" +
	"\vsource_path\x18\x02 \x01(\tR\n" +
	"sourcePath\x12\x14\n" +
	"\x05rules\x18\x03 \x03(\tR\x05rules\x12(\n" +
	"\x10fail_on_severity\x18\x04 \x01(\tR\x0efailOnSeverity\x12#\n" +
	"\routput_format\x18\x05 \x01(\tR\foutputFormat\"\xce\x01\n" +
	"\x14ScanContainerRequest\x12\x18\n" +
	"\ascanner\x18\x01 \x01(\tR\ascanner\x12!\n" +
	"\ftarget_image\x18\x02 \x01(\tR\vtargetImage\x12-\n" +
	"\x12severity_threshold\x18\x03 \x01(\tR\x11severityThreshold\x12%\n" +
	"\x0eignore_unfixed\x18\x04 \x01(\bR\rignoreUnfixed\x12#\n" +
	"\routput_format\x18\x05 \x01(\tR\foutputFormat\"\x9b\x01\n" +
	"\x0fScanDepsRequest\x12\x18\n" +
	"\ascanner\x18\x01 \x01(\tR\ascanner\x12\x1f\n" +
	"\vsource_path\x18\x02 \x01(\tR\n" +
	"sourcePath\x12(\n" +
	"\x10fail_on_severity\x18\x03 \x01(\tR\x0efailOnSeverity\x12#\n" +
	"\routput_format\x18\x04 \x01(\tR\foutputFormat\"\x88\x01\n" +
	"\aFinding\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x12\n" +
	"\x04line\x18\x05 \x01(\x05R\x04line\"w\n" +
	"\aSummary\x12\x1a\n" +
	"\bcritical\x18\x01 \x01(\x05R\bcritical\x12\x12\n" +
	"\x04high\x18\x02 \x01(\x05R\x04high\x12\x16\n" +
	"\x06medium\x18\x03 \x01(\x05R\x06medium\x12\x10\n" +
	"\x03low\x18\x04 \x01(\x05R\x03low\x12\x12\n" +
	"\x04info\x18\x05 \x01(\x05R\x04info\"\xf1\x01\n" +
	"\n" +
	"ScanOutput\x12\x18\n" +
	"\ascanner\x18\x01 \x01(\tR\ascanner\x12\x1f\n" +
	"\vpassed_gate\x18\x02 \x01(\bR\n" +
	"passedGate\x12I\n" +
	"\bfindings\x18\x03 \x03(\v2-.workflow.plugins.security_scanner.v1.FindingR\bfindings\x12G\n" +
	"\asummary\x18\x04 \x01(\v2-.workflow.plugins.security_scanner.v1.SummaryR\asummary\x12\x14\n" +
	"\x05error\x18d \x01(\tR\x05errorBVZTgithub.com/GoCodeAlone/workflow-plugin-security-scanner/internal/contracts;contractsb\x06proto3"

var (
	file_internal_contracts_security_scanner_proto_rawDescOnce sync.Once
	file_internal_contracts_security_scanner_proto_rawDescData []byte
)

func file_internal_contracts_security_scanner_proto_rawDescGZIP() []byte {
	file_internal_contracts_security_scanner_proto_rawDescOnce.Do(func() {
		file_internal_contracts_security_scanner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_contracts_security_scanner_proto_rawDesc), len(file_internal_contracts_security_scanner_proto_rawDesc)))
	})
	return file_internal_contracts_security_scanner_proto_rawDescData
}

var file_internal_contracts_security_scanner_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_contracts_security_scanner_proto_goTypes = []any{
	(*ScannerModuleConfig)(nil),  // 0: workflow.plugins.security_scanner.v1.ScannerModuleConfig
	(*SASTScanConfig)(nil),       // 1: workflow.plugins.security_scanner.v1.SASTScanConfig
	(*SASTScanInput)(nil),        // 2: workflow.plugins.security_scanner.v1.SASTScanInput
	(*ContainerScanConfig)(nil),  // 3: workflow.plugins.security_scanner.v1.ContainerScanConfig
	(*ContainerScanInput)(nil),   // 4: workflow.plugins.security_scanner.v1.ContainerScanInput
	(*DepsScanConfig)(nil),       // 5: workflow.plugins.security_scanner.v1.DepsScanConfig
	(*DepsScanInput)(nil),        // 6: workflow.plugins.security_scanner.v1.DepsScanInput
	(*ScanSASTRequest)(nil),      // 7: workflow.plugins.security_scanner.v1.ScanSASTRequest
	(*ScanContainerRequest)(nil), // 8: workflow.plugins.security_scanner.v1.ScanContainerRequest
	(*ScanDepsRequest)(nil),      // 9: workflow.plugins.security_scanner.v1.ScanDepsRequest
	(*Finding)(nil),              // 10: workflow.plugins.security_scanner.v1.Finding
	(*Summary)(nil),              // 11: workflow.plugins.security_scanner.v1.Summary
	(*ScanOutput)(nil),           // 12: workflow.plugins.security_scanner.v1.ScanOutput
}
var file_internal_contracts_security_scanner_proto_depIdxs = []int32{
	10, // 0: workflow.plugins.security_scanner.v1.ScannerModuleConfig.mock_findings:type_name -> workflow.plugins.security_scanner.v1.Finding
	10, // 1: workflow.plugins.security_scanner.v1.ScanOutput.findings:type_name -> workflow.plugins.security_scanner.v1.Finding
	11, // 2: workflow.plugins.security_scanner.v1.ScanOutput.summary:type_name -> workflow.plugins.security_scanner.v1.Summary
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_contracts_security_scanner_proto_init() }
func file_internal_contracts_security_scanner_proto_init() {
	if File_internal_contracts_security_scanner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_contracts_security_scanner_proto_rawDesc), len(file_internal_contracts_security_scanner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_contracts_security_scanner_proto_goTypes,
		DependencyIndexes: file_internal_contracts_security_scanner_proto_depIdxs,
		MessageInfos:      file_internal_contracts_security_scanner_proto_msgTypes,
	}.Build()
	File_internal_contracts_security_scanner_proto = out.File
	file_internal_contracts_security_scanner_proto_goTypes = nil
	file_internal_contracts_security_scanner_proto_depIdxs = nil
}
